"""SPINE function metadata generated from spine-go's model by tools/gen_schema.py.

Do not edit by hand.
"""

# function -> (list field, key fields, primary key fields)
LIST_FUNCTIONS: dict[str, tuple[str, tuple[str, ...], tuple[str, ...]]] = {
    'alarmListData': ('alarmData', ('alarmId',), ('alarmId',)),
    'billConstraintsListData': ('billConstraintsData', ('billId',), ('billId',)),
    'billDescriptionListData': ('billDescriptionData', ('billId',), ('billId',)),
    'billListData': ('billData', ('billId',), ('billId',)),
    'bindingManagementEntryListData': ('bindingManagementEntryData', ('bindingId',), ('bindingId',)),
    'commodityListData': ('commodityData', ('commodityId',), ('commodityId',)),
    'deviceConfigurationKeyValueConstraintsListData': ('deviceConfigurationKeyValueConstraintsData', ('keyId',), ('keyId',)),
    'deviceConfigurationKeyValueDescriptionListData': ('deviceConfigurationKeyValueDescriptionData', ('keyId',), ('keyId',)),
    'deviceConfigurationKeyValueListData': ('deviceConfigurationKeyValueData', ('keyId',), ('keyId',)),
    'electricalConnectionCharacteristicListData': ('electricalConnectionCharacteristicData', ('electricalConnectionId', 'parameterId', 'characteristicId'), ('electricalConnectionId',)),
    'electricalConnectionDescriptionListData': ('electricalConnectionDescriptionData', ('electricalConnectionId',), ()),
    'electricalConnectionParameterDescriptionListData': ('electricalConnectionParameterDescriptionData', ('electricalConnectionId', 'parameterId'), ('electricalConnectionId',)),
    'electricalConnectionPermittedValueSetListData': ('electricalConnectionPermittedValueSetData', ('electricalConnectionId', 'parameterId'), ('electricalConnectionId',)),
    'electricalConnectionStateListData': ('electricalConnectionStateData', ('electricalConnectionId',), ()),
    'hvacOperationModeDescriptionListData': ('hvacOperationModeDescriptionData', ('operationModeId',), ('operationModeId',)),
    'hvacOverrunDescriptionListData': ('hvacOverrunDescriptionData', ('overrunId',), ('overrunId',)),
    'hvacOverrunListData': ('hvacOverrunData', ('overrunId',), ('overrunId',)),
    'hvacSystemFunctionDescriptionListData': ('hvacSystemFunctionDescriptionData', ('systemFunctionId',), ('systemFunctionId',)),
    'hvacSystemFunctionListData': ('hvacSystemFunctionData', ('systemFunctionId',), ('systemFunctionId',)),
    'hvacSystemFunctionOperationModeRelationListData': ('hvacSystemFunctionOperationModeRelationData', ('systemFunctionId',), ('systemFunctionId',)),
    'hvacSystemFunctionPowerSequenceRelationListData': ('hvacSystemFunctionPowerSequenceRelationData', ('systemFunctionId',), ('systemFunctionId',)),
    'hvacSystemFunctionSetpointRelationListData': ('hvacSystemFunctionSetpointRelationData', ('systemFunctionId', 'operationModeId'), ('systemFunctionId',)),
    'identificationListData': ('identificationData', ('identificationId',), ('identificationId',)),
    'incentiveDescriptionListData': ('incentiveDescriptionData', ('incentiveId',), ('incentiveId',)),
    'incentiveListData': ('incentiveData', ('incentiveId',), ('incentiveId',)),
    'loadControlEventListData': ('loadControlEventData', ('eventId',), ('eventId',)),
    'loadControlLimitConstraintsListData': ('loadControlLimitConstraintsData', ('limitId',), ('limitId',)),
    'loadControlLimitDescriptionListData': ('loadControlLimitDescriptionData', ('limitId',), ('limitId',)),
    'loadControlLimitListData': ('loadControlLimitData', ('limitId',), ('limitId',)),
    'loadControlStateListData': ('loadControlStateData', ('eventId',), ('eventId',)),
    'measurementConstraintsListData': ('measurementConstraintsData', ('measurementId',), ('measurementId',)),
    'measurementDescriptionListData': ('measurementDescriptionData', ('measurementId',), ('measurementId',)),
    'measurementListData': ('measurementData', ('measurementId', 'valueType'), ('measurementId',)),
    'measurementSeriesListData': ('measurementSeriesData', ('measurementId', 'valueType', 'timestamp'), ('measurementId',)),
    'measurementThresholdRelationListData': ('measurementThresholdRelationData', ('measurementId',), ('measurementId',)),
    'messagingListData': ('messagingData', ('messagingNumber',), ('messagingNumber',)),
    'networkManagementDeviceDescriptionListData': ('networkManagementDeviceDescriptionData', ('deviceAddress',), ('deviceAddress',)),
    'networkManagementEntityDescriptionListData': ('networkManagementEntityDescriptionData', ('entityAddress',), ('entityAddress',)),
    'networkManagementFeatureDescriptionListData': ('networkManagementFeatureDescriptionData', ('featureAddress',), ('featureAddress',)),
    'nodeManagementDestinationListData': ('nodeManagementDestinationData', (), ()),
    'operatingConstraintsDurationListData': ('operatingConstraintsDurationData', ('sequenceId',), ('sequenceId',)),
    'operatingConstraintsInterruptListData': ('operatingConstraintsInterruptData', ('sequenceId',), ('sequenceId',)),
    'operatingConstraintsPowerDescriptionListData': ('operatingConstraintsPowerDescriptionData', ('sequenceId',), ('sequenceId',)),
    'operatingConstraintsPowerLevelListData': ('operatingConstraintsPowerLevelData', ('sequenceId',), ('sequenceId',)),
    'operatingConstraintsPowerRangeListData': ('operatingConstraintsPowerRangeData', ('sequenceId',), ('sequenceId',)),
    'operatingConstraintsResumeImplicationListData': ('operatingConstraintsResumeImplicationData', ('sequenceId',), ('sequenceId',)),
    'powerSequenceAlternativesRelationListData': ('powerSequenceAlternativesRelationData', ('alternativesId',), ('alternativesId',)),
    'powerSequenceDescriptionListData': ('powerSequenceDescriptionData', ('sequenceId',), ('sequenceId',)),
    'powerSequencePriceListData': ('powerSequencePriceData', ('sequenceId',), ('sequenceId',)),
    'powerSequenceScheduleConstraintsListData': ('powerSequenceScheduleConstraintsData', ('sequenceId',), ('sequenceId',)),
    'powerSequenceScheduleListData': ('powerSequenceScheduleData', ('sequenceId',), ('sequenceId',)),
    'powerSequenceSchedulePreferenceListData': ('powerSequenceSchedulePreferenceData', ('sequenceId',), ('sequenceId',)),
    'powerSequenceStateListData': ('powerSequenceStateData', ('sequenceId',), ('sequenceId',)),
    'powerTimeSlotScheduleConstraintsListData': ('powerTimeSlotScheduleConstraintsData', ('sequenceId',), ('sequenceId',)),
    'powerTimeSlotScheduleListData': ('powerTimeSlotScheduleData', ('sequenceId',), ('sequenceId',)),
    'powerTimeSlotValueListData': ('powerTimeSlotValueData', ('sequenceId',), ('sequenceId',)),
    'sessionIdentificationListData': ('sessionIdentificationData', ('sessionId',), ('sessionId',)),
    'sessionMeasurementRelationListData': ('sessionMeasurementRelationData', ('sessionId',), ('sessionId',)),
    'setpointDescriptionListData': ('setpointDescriptionData', ('setpointId', 'measurementId', 'timeTableId'), ('setpointId',)),
    'setpointListData': ('setpointData', ('setpointId',), ('setpointId',)),
    'specificationVersionListData': ('specificationVersionData', (), ()),
    'stateInformationListData': ('stateInformationData', ('stateInformationId',), ('stateInformationId',)),
    'subscriptionManagementEntryListData': ('subscriptionManagementEntryData', ('subscriptionId',), ('subscriptionId',)),
    'supplyConditionDescriptionListData': ('supplyConditionDescriptionData', ('conditionId',), ('conditionId',)),
    'supplyConditionListData': ('supplyConditionData', ('conditionId',), ('conditionId',)),
    'supplyConditionThresholdRelationListData': ('SupplyConditionThresholdRelationDataType', ('conditionId',), ('conditionId',)),
    'tariffBoundaryRelationListData': ('tariffBoundaryRelationData', ('tariffId',), ('tariffId',)),
    'tariffDescriptionListData': ('tariffDescriptionData', ('tariffId',), ('tariffId',)),
    'tariffListData': ('tariffData', ('tariffId',), ('tariffId',)),
    'tariffTierRelationListData': ('tariffTierRelationData', ('tariffId',), ('tariffId',)),
    'taskManagementJobDescriptionListData': ('taskManagementJobDescriptionData', ('jobId',), ('jobId',)),
    'taskManagementJobListData': ('taskManagementJobData', ('jobId',), ('jobId',)),
    'taskManagementJobRelationListData': ('taskManagementJobRelationData', ('jobId',), ('jobId',)),
    'thresholdConstraintsListData': ('thresholdConstraintsData', ('thresholdId',), ('thresholdId',)),
    'thresholdDescriptionListData': ('thresholdDescriptionData', ('thresholdId',), ('thresholdId',)),
    'thresholdListData': ('thresholdData', ('thresholdId',), ('thresholdId',)),
    'tierBoundaryDescriptionListData': ('tierBoundaryDescriptionData', ('boundaryId',), ('boundaryId',)),
    'tierBoundaryListData': ('tierBoundaryData', ('boundaryId',), ('boundaryId',)),
    'tierDescriptionListData': ('tierDescriptionData', ('tierId',), ('tierId',)),
    'tierIncentiveRelationListData': ('tierIncentiveRelationData', ('tierId',), ('tierId',)),
    'tierListData': ('tierData', ('tierId',), ('tierId',)),
    'timeSeriesConstraintsListData': ('timeSeriesConstraintsData', ('timeSeriesId',), ('timeSeriesId',)),
    'timeSeriesDescriptionListData': ('timeSeriesDescriptionData', ('timeSeriesId',), ('timeSeriesId',)),
    'timeSeriesListData': ('timeSeriesData', ('timeSeriesId',), ('timeSeriesId',)),
    'timeTableConstraintsListData': ('timeTableConstraintsData', ('timeTableId',), ('timeTableId',)),
    'timeTableDescriptionListData': ('timeTableDescriptionData', ('timeTableId',), ('timeTableId',)),
    'timeTableListData': ('timeTableData', ('timeTableId', 'timeSlotId'), ('timeTableId',)),
}

# all functions known to the data model
FUNCTIONS: frozenset[str] = frozenset({
    'actuatorLevelData',
    'actuatorLevelDescriptionData',
    'actuatorSwitchData',
    'actuatorSwitchDescriptionData',
    'alarmListData',
    'billConstraintsListData',
    'billDescriptionListData',
    'billListData',
    'bindingManagementDeleteCall',
    'bindingManagementEntryListData',
    'bindingManagementRequestCall',
    'commodityListData',
    'dataTunnelingCall',
    'deviceClassificationManufacturerData',
    'deviceClassificationUserData',
    'deviceConfigurationKeyValueConstraintsListData',
    'deviceConfigurationKeyValueDescriptionListData',
    'deviceConfigurationKeyValueListData',
    'deviceDiagnosisHeartbeatData',
    'deviceDiagnosisServiceData',
    'deviceDiagnosisStateData',
    'directControlActivityListData',
    'directControlDescriptionData',
    'electricalConnectionCharacteristicData',
    'electricalConnectionCharacteristicListData',
    'electricalConnectionDescriptionListData',
    'electricalConnectionParameterDescriptionListData',
    'electricalConnectionPermittedValueSetListData',
    'electricalConnectionStateListData',
    'hvacOperationModeDescriptionListData',
    'hvacOverrunDescriptionListData',
    'hvacOverrunListData',
    'hvacSystemFunctionDescriptionListData',
    'hvacSystemFunctionListData',
    'hvacSystemFunctionOperationModeRelationListData',
    'hvacSystemFunctionPowerSequenceRelationListData',
    'hvacSystemFunctionSetpointRelationListData',
    'identificationListData',
    'incentiveDescriptionListData',
    'incentiveListData',
    'incentiveTableConstraintsData',
    'incentiveTableData',
    'incentiveTableDescriptionData',
    'loadControlEventListData',
    'loadControlLimitConstraintsListData',
    'loadControlLimitDescriptionListData',
    'loadControlLimitListData',
    'loadControlNodeData',
    'loadControlStateListData',
    'measurementConstraintsListData',
    'measurementDescriptionListData',
    'measurementListData',
    'measurementSeriesListData',
    'measurementThresholdRelationListData',
    'messagingListData',
    'networkManagementAbortCall',
    'networkManagementAddNodeCall',
    'networkManagementDeviceDescriptionListData',
    'networkManagementDiscoverCall',
    'networkManagementEntityDescriptionListData',
    'networkManagementFeatureDescriptionListData',
    'networkManagementJoiningModeData',
    'networkManagementModifyNodeCall',
    'networkManagementProcessStateData',
    'networkManagementRemoveNodeCall',
    'networkManagementReportCandidateData',
    'networkManagementScanNetworkCall',
    'nodeManagementBindingData',
    'nodeManagementBindingDeleteCall',
    'nodeManagementBindingRequestCall',
    'nodeManagementDestinationListData',
    'nodeManagementDetailedDiscoveryData',
    'nodeManagementSubscriptionData',
    'nodeManagementSubscriptionDeleteCall',
    'nodeManagementSubscriptionRequestCall',
    'nodeManagementUseCaseData',
    'operatingConstraintsDurationListData',
    'operatingConstraintsInterruptListData',
    'operatingConstraintsPowerDescriptionListData',
    'operatingConstraintsPowerLevelListData',
    'operatingConstraintsPowerRangeListData',
    'operatingConstraintsResumeImplicationListData',
    'powerSequenceAlternativesRelationListData',
    'powerSequenceDescriptionListData',
    'powerSequenceNodeScheduleInformationData',
    'powerSequencePriceCalculationRequestCall',
    'powerSequencePriceListData',
    'powerSequenceScheduleConfigurationRequestCall',
    'powerSequenceScheduleConstraintsListData',
    'powerSequenceScheduleListData',
    'powerSequenceSchedulePreferenceListData',
    'powerSequenceStateListData',
    'powerTimeSlotScheduleConstraintsListData',
    'powerTimeSlotScheduleListData',
    'powerTimeSlotValueListData',
    'resultData',
    'sensingDescriptionData',
    'sensingListData',
    'sessionIdentificationListData',
    'sessionMeasurementRelationListData',
    'setpointConstraintsListData',
    'setpointDescriptionListData',
    'setpointListData',
    'smartEnergyManagementPsConfigurationRequestCall',
    'smartEnergyManagementPsData',
    'smartEnergyManagementPsPriceCalculationRequestCall',
    'smartEnergyManagementPsPriceData',
    'specificationVersionListData',
    'stateInformationListData',
    'subscriptionManagementDeleteCall',
    'subscriptionManagementEntryListData',
    'subscriptionManagementRequestCall',
    'supplyConditionDescriptionListData',
    'supplyConditionListData',
    'supplyConditionThresholdRelationListData',
    'tariffBoundaryRelationListData',
    'tariffDescriptionListData',
    'tariffListData',
    'tariffOverallConstraintsData',
    'tariffTierRelationListData',
    'taskManagementJobDescriptionListData',
    'taskManagementJobListData',
    'taskManagementJobRelationListData',
    'taskManagementOverviewData',
    'thresholdConstraintsListData',
    'thresholdDescriptionListData',
    'thresholdListData',
    'tierBoundaryDescriptionListData',
    'tierBoundaryListData',
    'tierDescriptionListData',
    'tierIncentiveRelationListData',
    'tierListData',
    'timeDistributorData',
    'timeDistributorEnquiryCall',
    'timeInformationData',
    'timePrecisionData',
    'timeSeriesConstraintsListData',
    'timeSeriesDescriptionListData',
    'timeSeriesListData',
    'timeTableConstraintsListData',
    'timeTableDescriptionListData',
    'timeTableListData',
    'useCaseInformationListData',
})

SELECTORS: dict[str, str] = {
    'alarmListData': 'alarmListDataSelectors',
    'billConstraintsListData': 'billConstraintsListDataSelectors',
    'billDescriptionListData': 'billDescriptionListDataSelectors',
    'billListData': 'billListDataSelectors',
    'bindingManagementEntryListData': 'bindingManagementEntryListDataSelectors',
    'commodityListData': 'commodityListDataSelectors',
    'deviceConfigurationKeyValueConstraintsListData': 'deviceConfigurationKeyValueConstraintsListDataSelectors',
    'deviceConfigurationKeyValueDescriptionListData': 'deviceConfigurationKeyValueDescriptionListDataSelectors',
    'deviceConfigurationKeyValueListData': 'deviceConfigurationKeyValueListDataSelectors',
    'directControlActivityListData': 'directControlActivityListDataSelectors',
    'electricalConnectionCharacteristicListData': 'electricalConnectionCharacteristicListDataSelectors',
    'electricalConnectionDescriptionListData': 'electricalConnectionDescriptionListDataSelectors',
    'electricalConnectionParameterDescriptionListData': 'electricalConnectionParameterDescriptionListDataSelectors',
    'electricalConnectionPermittedValueSetListData': 'electricalConnectionPermittedValueSetListDataSelectors',
    'electricalConnectionStateListData': 'electricalConnectionStateListDataSelectors',
    'hvacOperationModeDescriptionListData': 'hvacOperationModeDescriptionListDataSelectors',
    'hvacOverrunDescriptionListData': 'hvacOverrunDescriptionListDataSelectors',
    'hvacOverrunListData': 'hvacOverrunListDataSelectors',
    'hvacSystemFunctionDescriptionListData': 'hvacSystemFunctionDescriptionListDataSelectors',
    'hvacSystemFunctionListData': 'hvacSystemFunctionListDataSelectors',
    'hvacSystemFunctionOperationModeRelationListData': 'hvacSystemFunctionOperationModeRelationListDataSelectors',
    'hvacSystemFunctionPowerSequenceRelationListData': 'hvacSystemFunctionPowerSequenceRelationListDataSelectors',
    'hvacSystemFunctionSetpointRelationListData': 'hvacSystemFunctionSetpointRelationListDataSelectors',
    'identificationListData': 'identificationListDataSelectors',
    'incentiveDescriptionListData': 'incentiveDescriptionListDataSelectors',
    'incentiveListData': 'incentiveListDataSelectors',
    'incentiveTableConstraintsData': 'incentiveTableConstraintsDataSelectors',
    'incentiveTableData': 'incentiveTableDataSelectors',
    'incentiveTableDescriptionData': 'incentiveTableDescriptionDataSelectors',
    'loadControlEventListData': 'loadControlEventListDataSelectors',
    'loadControlLimitConstraintsListData': 'loadControlLimitConstraintsListDataSelectors',
    'loadControlLimitDescriptionListData': 'loadControlLimitDescriptionListDataSelectors',
    'loadControlLimitListData': 'loadControlLimitListDataSelectors',
    'loadControlStateListData': 'loadControlStateListDataSelectors',
    'measurementConstraintsListData': 'measurementConstraintsListDataSelectors',
    'measurementDescriptionListData': 'measurementDescriptionListDataSelectors',
    'measurementListData': 'measurementListDataSelectors',
    'measurementSeriesListData': 'measurementSeriesListDataSelectors',
    'measurementThresholdRelationListData': 'measurementThresholdRelationListDataSelectors',
    'messagingListData': 'messagingListDataSelectors',
    'networkManagementDeviceDescriptionListData': 'networkManagementDeviceDescriptionListDataSelectors',
    'networkManagementEntityDescriptionListData': 'networkManagementEntityDescriptionListDataSelectors',
    'networkManagementFeatureDescriptionList': 'networkManagementFeatureDescriptionListDataSelectors',
    'nodeManagementBindingData': 'nodeManagementBindingDataSelectors',
    'nodeManagementDestinationListData': 'nodeManagementDestinationListDataSelectors',
    'nodeManagementDetailedDiscoveryData': 'nodeManagementDetailedDiscoveryDataSelectors',
    'nodeManagementSubscriptionData': 'nodeManagementSubscriptionDataSelectors',
    'nodeManagementUseCaseData': 'nodeManagementUseCaseDataSelectors',
    'operatingConstraintsDurationListData': 'operatingConstraintsDurationListDataSelectors',
    'operatingConstraintsInterruptListData': 'operatingConstraintsInterruptListDataSelectors',
    'operatingConstraintsPowerDescriptionListData': 'operatingConstraintsPowerDescriptionListDataSelectors',
    'operatingConstraintsPowerLevelListData': 'operatingConstraintsPowerLevelListDataSelectors',
    'operatingConstraintsPowerRangeListData': 'operatingConstraintsPowerRangeListDataSelectors',
    'operatingConstraintsResumeImplicationListData': 'operatingConstraintsResumeImplicationListDataSelectors',
    'powerSequenceAlternativesRelationListData': 'powerSequenceAlternativesRelationListDataSelectors',
    'powerSequenceDescriptionListData': 'powerSequenceDescriptionListDataSelectors',
    'powerSequencePriceListData': 'powerSequencePriceListDataSelectors',
    'powerSequenceScheduleConstraintsListData': 'powerSequenceScheduleConstraintsListDataSelectors',
    'powerSequenceScheduleListData': 'powerSequenceScheduleListDataSelectors',
    'powerSequenceSchedulePreferenceListData': 'powerSequenceSchedulePreferenceListDataSelectors',
    'powerSequenceStateListData': 'powerSequenceStateListDataSelectors',
    'powerTimeSlotScheduleConstraintsListData': 'powerTimeSlotScheduleConstraintsListDataSelectors',
    'powerTimeSlotScheduleListData': 'powerTimeSlotScheduleListDataSelectors',
    'powerTimeSlotValueListData': 'powerTimeSlotValueListDataSelectors',
    'sensingListData': 'sensingListDataSelectors',
    'sessionIdentificationListData': 'sessionIdentificationListDataSelectors',
    'sessionMeasurementRelationListData': 'sessionMeasurementRelationListDataSelectors',
    'setpointConstraintsListData': 'setpointConstraintsListDataSelectors',
    'setpointDescriptionListData': 'setpointDescriptionListDataSelectors',
    'setpointListData': 'setpointListDataSelectors',
    'smartEnergyManagementPsData': 'smartEnergyManagementPsDataSelectors',
    'smartEnergyManagementPsPriceData': 'smartEnergyManagementPsPriceDataSelectors',
    'specificationVersionListData': 'specificationVersionListDataSelectors',
    'stateInformationListData': 'stateInformationListDataSelectors',
    'subscriptionManagementEntryListData': 'subscriptionManagementEntryListDataSelectors',
    'supplyConditionDescriptionListData': 'supplyConditionDescriptionListDataSelectors',
    'supplyConditionListData': 'supplyConditionListDataSelectors',
    'supplyConditionThresholdRelationListData': 'supplyConditionThresholdRelationListDataSelectors',
    'tariffBoundaryRelationListData': 'tariffBoundaryRelationListDataSelectors',
    'tariffDescriptionListData': 'tariffDescriptionListDataSelectors',
    'tariffListData': 'tariffListDataSelectors',
    'tariffTierRelationListData': 'tariffTierRelationListDataSelectors',
    'taskManagementJobDescriptionListData': 'taskManagementJobDescriptionListDataSelectors',
    'taskManagementJobListData': 'taskManagementJobListDataSelectors',
    'taskManagementJobRelationListData': 'taskManagementJobRelationListDataSelectors',
    'thresholdConstraintsListData': 'thresholdConstraintsListDataSelectors',
    'thresholdDescriptionListData': 'thresholdDescriptionListDataSelectors',
    'thresholdListData': 'thresholdListDataSelectors',
    'tierBoundaryDescriptionListData': 'tierBoundaryDescriptionListDataSelectors',
    'tierBoundaryListData': 'tierBoundaryListDataSelectors',
    'tierDescriptionListData': 'tierDescriptionListDataSelectors',
    'tierIncentiveRelationListData': 'tierIncentiveRelationListDataSelectors',
    'tierListData': 'tierListDataSelectors',
    'timeSeriesConstraintsListData': 'timeSeriesConstraintsListDataSelectors',
    'timeSeriesDescriptionListData': 'timeSeriesDescriptionListDataSelectors',
    'timeSeriesListData': 'timeSeriesListDataSelectors',
    'timeTableConstraintsListData': 'timeTableConstraintsListDataSelectors',
    'timeTableDescriptionListData': 'timeTableDescriptionListDataSelectors',
    'timeTableListData': 'timeTableListDataSelectors',
    'useCaseInformationListData': 'useCaseInformationListDataSelectors',
}

ELEMENTS: dict[str, str] = {
    'actuatorLevelData': 'actuatorLevelDataElements',
    'actuatorLevelDescriptionData': 'actuatorLevelDescriptionDataElements',
    'actuatorSwitchData': 'actuatorSwitchDataElements',
    'actuatorSwitchDescriptionData': 'actuatorSwitchDescriptionDataElements',
    'alarmListData': 'alarmDataElements',
    'billConstraintsListData': 'billConstraintsDataElements',
    'billDescriptionListData': 'billDescriptionDataElements',
    'billListData': 'billDataElements',
    'bindingManagementDeleteCall': 'bindingManagementDeleteCallElements',
    'bindingManagementEntryListData': 'bindingManagementEntryDataElements',
    'bindingManagementRequestCall': 'bindingManagementRequestCallElements',
    'commodityListData': 'commodityDataElements',
    'dataTunnelingCall': 'dataTunnelingCallElements',
    'deviceClassificationManufacturerData': 'deviceClassificationManufacturerDataElements',
    'deviceClassificationUserData': 'deviceClassificationUserDataElements',
    'deviceConfigurationKeyValueConstraintsListData': 'deviceConfigurationKeyValueConstraintsDataElements',
    'deviceConfigurationKeyValueDescriptionListData': 'deviceConfigurationKeyValueDescriptionDataElements',
    'deviceConfigurationKeyValueListData': 'deviceConfigurationKeyValueDataElements',
    'deviceDiagnosisHeartbeatData': 'deviceDiagnosisHeartbeatDataElements',
    'deviceDiagnosisServiceData': 'deviceDiagnosisServiceDataElements',
    'deviceDiagnosisStateData': 'deviceDiagnosisStateDataElements',
    'directControlActivityListData': 'directControlActivityDataElements',
    'directControlDescriptionData': 'directControlDescriptionDataElements',
    'electricalConnectionCharacteristicListData': 'electricalConnectionCharacteristicDataElements',
    'electricalConnectionDescriptionListData': 'electricalConnectionDescriptionDataElements',
    'electricalConnectionParameterDescriptionListData': 'electricalConnectionParameterDescriptionDataElements',
    'electricalConnectionPermittedValueSetListData': 'electricalConnectionPermittedValueSetDataElements',
    'electricalConnectionStateListData': 'electricalConnectionStateDataElements',
    'hvacOperationModeDescriptionListData': 'hvacOperationModeDescriptionDataElements',
    'hvacOverrunDescriptionListData': 'hvacOverrunDescriptionDataElements',
    'hvacOverrunListData': 'hvacOverrunDataElements',
    'hvacSystemFunctionDescriptionListData': 'hvacSystemFunctionDescriptionDataElements',
    'hvacSystemFunctionListData': 'hvacSystemFunctionDataElements',
    'hvacSystemFunctionOperationModeRelationListData': 'hvacSystemFunctionOperationModeRelationDataElements',
    'hvacSystemFunctionPowerSequenceRelationListData': 'hvacSystemFunctionPowerSequenceRelationDataElements',
    'hvacSystemFunctionSetpointRelationListData': 'hvacSystemFunctionSetpointRelationDataElements',
    'identificationListData': 'identificationDataElements',
    'incentiveDescriptionListData': 'incentiveDescriptionDataElements',
    'incentiveListData': 'incentiveDataElements',
    'incentiveTableConstraintsData': 'incentiveTableConstraintsDataElements',
    'incentiveTableData': 'incentiveTableDataElements',
    'incentiveTableDescriptionData': 'incentiveTableDescriptionDataElements',
    'loadControlEventListData': 'loadControlEventDataElements',
    'loadControlLimitConstraintsListData': 'loadControlLimitConstraintsDataElements',
    'loadControlLimitDescriptionListData': 'loadControlLimitDescriptionDataElements',
    'loadControlLimitListData': 'loadControlLimitDataElements',
    'loadControlNodeData': 'loadControlNodeDataElements',
    'loadControlStateListData': 'loadControlStateDataElements',
    'measurementConstraintsListData': 'measurementConstraintsDataElements',
    'measurementDescriptionListData': 'measurementDescriptionDataElements',
    'measurementListData': 'measurementDataElements',
    'measurementSeriesListData': 'measurementSeriesDataElements',
    'measurementThresholdRelationListData': 'measurementThresholdRelationDataElements',
    'messagingListData': 'messagingDataElements',
    'networkManagementAbortCall': 'networkManagementAbortCallElements',
    'networkManagementAddNodeCall': 'networkManagementAddNodeCallElements',
    'networkManagementDeviceDescriptionListData': 'networkManagementDeviceDescriptionDataElements',
    'networkManagementDiscoverCall': 'networkManagementDiscoverCallElements',
    'networkManagementEntityDescriptionListData': 'networkManagementEntityDescriptionDataElements',
    'networkManagementFeatureDescriptionListData': 'networkManagementFeatureDescriptionDataElements',
    'networkManagementJoiningModeData': 'networkManagementJoiningModeDataElements',
    'networkManagementModifyNodeCall': 'networkManagementModifyNodeCallElements',
    'networkManagementProcessStateData': 'networkManagementProcessStateDataElements',
    'networkManagementRemoveNodeCall': 'networkManagementRemoveNodeCallElements',
    'networkManagementReportCandidateData': 'networkManagementReportCandidateDataElements',
    'networkManagementScanNetworkCall': 'networkManagementScanNetworkCallElements',
    'nodeManagementBindingData': 'nodeManagementBindingDataElements',
    'nodeManagementBindingDeleteCall': 'nodeManagementBindingDeleteCallElements',
    'nodeManagementBindingRequestCall': 'nodeManagementBindingRequestCallElements',
    'nodeManagementDestinationListData': 'nodeManagementDestinationDataElements',
    'nodeManagementDetailedDiscoveryData': 'nodeManagementDetailedDiscoveryDataElements',
    'nodeManagementSubscriptionData': 'nodeManagementSubscriptionDataElements',
    'nodeManagementSubscriptionDeleteCall': 'nodeManagementSubscriptionDeleteCallElements',
    'nodeManagementSubscriptionRequestCall': 'nodeManagementSubscriptionRequestCallElements',
    'nodeManagementUseCaseData': 'nodeManagementUseCaseDataElements',
    'operatingConstraintsDurationListData': 'operatingConstraintsDurationDataElements',
    'operatingConstraintsInterruptListData': 'operatingConstraintsInterruptDataElements',
    'operatingConstraintsPowerDescriptionListData': 'operatingConstraintsPowerDescriptionDataElements',
    'operatingConstraintsPowerLevelListData': 'operatingConstraintsPowerLevelDataElements',
    'operatingConstraintsPowerRangeListData': 'operatingConstraintsPowerRangeDataElements',
    'operatingConstraintsResumeImplicationListData': 'operatingConstraintsResumeImplicationDataElements',
    'powerSequenceAlternativesRelationListData': 'powerSequenceAlternativesRelationDataElements',
    'powerSequenceDescriptionListData': 'powerSequenceDescriptionDataElements',
    'powerSequenceNodeScheduleInformationData': 'powerSequenceNodeScheduleInformationDataElements',
    'powerSequencePriceCalculationRequestCall': 'powerSequencePriceCalculationRequestCallElements',
    'powerSequencePriceListData': 'powerSequencePriceDataElements',
    'powerSequenceScheduleConfigurationRequestCall': 'powerSequenceScheduleConfigurationRequestCallElements',
    'powerSequenceScheduleConstraintsListData': 'powerSequenceScheduleConstraintsDataElements',
    'powerSequenceScheduleListData': 'powerSequenceScheduleDataElements',
    'powerSequenceSchedulePreferenceListData': 'powerSequenceSchedulePreferenceDataElements',
    'powerSequenceStateListData': 'powerSequenceStateDataElements',
    'powerTimeSlotScheduleConstraintsListData': 'powerTimeSlotScheduleConstraintsDataElements',
    'powerTimeSlotScheduleListData': 'powerTimeSlotScheduleDataElements',
    'powerTimeSlotValueListData': 'powerTimeSlotValueDataElements',
    'sensingDescriptionData': 'sensingDescriptionDataElements',
    'sensingListData': 'sensingDataElements',
    'sessionIdentificationData': 'sessionIdentificationDataElements',
    'sessionMeasurementRelationData': 'sessionMeasurementRelationDataElements',
    'setpointConstraintsListData': 'setpointConstraintsDataElements',
    'setpointDescriptionData': 'setpointDescriptionDataElements',
    'setpointListData': 'setpointDataElements',
    'smartEnergyManagementPsConfigurationRequestCall': 'smartEnergyManagementPsConfigurationRequestCallElements',
    'smartEnergyManagementPsData': 'smartEnergyManagementPsDataElements',
    'smartEnergyManagementPsPriceCalculationRequestCall': 'smartEnergyManagementPsPriceCalculationRequestCallElements',
    'smartEnergyManagementPsPriceData': 'smartEnergyManagementPsPriceDataElements',
    'specificationVersionListData': 'specificationVersionDataElements',
    'stateInformationListData': 'stateInformationDataElements',
    'subscriptionManagementDeleteCall': 'subscriptionManagementDeleteCallElements',
    'subscriptionManagementEntryListData': 'subscriptionManagementEntryDataElements',
    'subscriptionManagementRequestCall': 'subscriptionManagementRequestCallElements',
    'supplyConditionDescriptionListData': 'supplyConditionDescriptionDataElements',
    'supplyConditionListData': 'supplyConditionDataElements',
    'supplyConditionThresholdRelationListData': 'supplyConditionThresholdRelationDataElements',
    'tariffBoundaryRelationListData': 'tariffBoundaryRelationDataElements',
    'tariffDescriptionListData': 'tariffDescriptionDataElements',
    'tariffListData': 'tariffDataElements',
    'tariffOverallConstraintsData': 'tariffOverallConstraintsDataElements',
    'tariffTierRelationListData': 'tariffTierRelationDataElements',
    'taskManagementJobDescriptionListData': 'taskManagementJobDescriptionDataElements',
    'taskManagementJobListData': 'taskManagementJobDataElements',
    'taskManagementJobRelationListData': 'taskManagementJobRelationDataElements',
    'taskManagementOverviewData': 'taskManagementOverviewDataElements',
    'thresholdConstraintsListData': 'thresholdConstraintsDataElements',
    'thresholdDescriptionListData': 'thresholdDescriptionDataElements',
    'thresholdListData': 'thresholdDataElements',
    'tierBoundaryDescriptionListData': 'tierBoundaryDescriptionDataElements',
    'tierBoundaryListData': 'tierBoundaryDataElements',
    'tierDescriptionListData': 'tierDescriptionDataElements',
    'tierIncentiveRelationListData': 'tierIncentiveRelationDataElements',
    'tierListData': 'tierDataElements',
    'timeDistributorData': 'timeDistributorDataElements',
    'timeDistributorEnquiryCall': 'timeDistributorEnquiryCallElements',
    'timeInformationData': 'timeInformationDataElements',
    'timePrecisionData': 'timePrecisionDataElements',
    'timeSeriesConstraintsListData': 'timeSeriesConstraintsDataElements',
    'timeSeriesDescriptionListData': 'timeSeriesDescriptionDataElements',
    'timeSeriesListData': 'timeSeriesDataElements',
    'timeTableConstraintsListData': 'timeTableConstraintsDataElements',
    'timeTableDescriptionListData': 'timeTableDescriptionDataElements',
    'timeTableListData': 'timeTableDataElements',
    'useCaseInformationListData': 'useCaseInformationDataElements',
}
